services:
  backend:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.$AWS_REGION.amazonaws.com/${DOCKER_BACKEND_IMAGE}:latest
    container_name: ${DOCKER_BACKEND_CONTAINER}
    volumes:
      - frontend-access:${DIRECTORY_DOCKER_BACKEND_FRONTEND}
    ports:
      - "8080:8080"
    networks:
      - blog2025-stg-docker-network

  frontend:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.$AWS_REGION.amazonaws.com/${DOCKER_FRONTEND_IMAGE}:latest
    container_name: ${DOCKER_FRONTEND_CONTAINER}
    volumes:
      - frontend-access:${DIRECTORY_DOCKER_FRONTEND}
    ports:
      - "80:80"
    networks:
      - blog2025-stg-docker-network

volumes:
  frontend-access:

networks:
  blog2025-stg-docker-network:
    external: true
