version: 0.0
os: linux

hooks:
  BeforeInstall:
    - location: scripts/setup_docker_network.sh
      runas: ec2-user
    - location: scripts/login_ecr.sh
      runas: ec2-user
  AfterInstall:
    - location: scripts/deploy_image_backend.sh
      runas: ec2-user
    - location: scripts/deploy_image_frontend.sh
      runas: ec2-user
  ApplicationStart:
    - location: scripts/build_containers.sh
      runas: ec2-user
  ValidateService:
    - location: scripts/verify_containers.sh
      runas: ec2-user
