
CREATE TABLE m_country (
  id INT PRIMARY KEY,
  name_en VARCHAR(63) NOT NULL,
  name_ja VARCHAR(31) NOT NULL,
  iso_2 char(2) NOT NULL,
  iso_3 char(3) NOT NULL,
  icon_base VARCHAR(63) NOT NULL,
  update_timestamp timestamp default current_timestamp on update current_timestamp,
  insert_timestamp timestamp default current_timestamp,
  UNIQUE(iso_2)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('1','No Country','国籍なし','--','---','None');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('4','Afghanistan','アフガニスタン・イスラム共和国','af','afg','Afghanistan');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('248','Åland Islands','オーランド諸島','ax','ala','Åland-Islands');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('8','Albania','アルバニア共和国','al','alb','Albania');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('12','Algeria','アルジェリア民主人民共和国','dz','dza','Algeria');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('16','American Samoa','米領サモア','as','asm','American-Samoa');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('20','Andorra','アンドラ公国','ad','and','Andorra');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('24','Angola','アンゴラ共和国','ao','ago','Angola');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('660','Anguilla','アンギラ','ai','aia','Anguilla');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('10','Antarctica','南極','aq','ata','Antarctica');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('28','Antigua and Barbuda','アンティグア・バーブーダ','ag','atg','Antigua-and-Barbuda');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('32','Argentina','アルゼンチン共和国','ar','arg','Argentina');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('51','Armenia','アルメニア共和国','am','arm','Armenia');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('533','Aruba','アルバ','aw','abw','Aruba');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('36','Australia','オーストラリア連邦','au','aus','Australia');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('40','Austria','オーストリア共和国','at','aut','Austria');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('31','Azerbaijan','アゼルバイジャン共和国','az','aze','Azerbaijan');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('44','Bahamas','バハマ国','bs','bhs','Bahamas');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('48','Bahrain','バーレーン王国','bh','bhr','Bahrain');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('50','Bangladesh','バングラデシュ人民共和国','bd','bgd','Bangladesh');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('52','Barbados','バルバドス','bb','brb','Barbados');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('112','Belarus','ベラルーシ共和国','by','blr','Belarus');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('56','Belgium','ベルギー王国','be','bel','Belgium');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('84','Belize','ベリーズ','bz','blz','Belize');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('204','Benin','ベナン共和国','bj','ben','Benin');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('60','Bermuda','バミューダ諸島','bm','bmu','Bermuda');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('64','Bhutan','ブータン王国','bt','btn','Bhutan');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('68','Bolivia, Plurinational State of','ボリビア多民族国','bo','bol','Bolivia-Plurinational-State-of');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('535','Bonaire, Saint Eustatius and Saba','ボネール、シント・ユースタティウスおよびサバ','bq','bes','Bonaire-Saint-Eustatius-and-Saba');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('70','Bosnia and Herzegovina','ボスニア・ヘルツェゴビナ','ba','bih','Bosnia-and-Herzegovina');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('72','Botswana','ボツワナ共和国','bw','bwa','Botswana');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('74','Bouvet Island','ブーベ島','bv','bvt','Bouvet-Island');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('76','Brazil','ブラジル連邦共和国','br','bra','Brazil');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('86','British Indian Ocean Territory','英領インド洋地域','io','iot','British-Indian-Ocean-Territory');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('96','Brunei Darussalam','ブルネイ・ダルサラーム国','bn','brn','Brunei-Darussalam');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('100','Bulgaria','ブルガリア共和国','bg','bgr','Bulgaria');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('854','Burkina Faso','ブルキナファソ','bf','bfa','Burkina-Faso');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('108','Burundi','ブルンジ共和国','bi','bdi','Burundi');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('116','Cambodia','カンボジア王国','kh','khm','Cambodia');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('120','Cameroon','カメルーン共和国','cm','cmr','Cameroon');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('124','Canada','カナダ','ca','can','Canada');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('132','Cape Verde','カーボベルデ共和国','cv','cpv','Cape-Verde');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('136','Cayman Islands','ケイマン諸島','ky','cym','Cayman-Islands');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('140','Central African Republic','中央アフリカ共和国','cf','caf','Central-African-Republic');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('148','Chad','チャド共和国','td','tcd','Chad');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('152','Chile','チリ共和国','cl','chl','Chile');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('156','China','中華人民共和国','cn','chn','China');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('162','Christmas Island','クリスマス島','cx','cxr','Christmas-Island');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('166','Cocos (Keeling) Islands','ココス諸島','cc','cck','Cocos-(Keeling)-Islands');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('170','Colombia','コロンビア共和国','co','col','Colombia');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('174','Comoros','コモロ連合','km','com','Comoros');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('178','Congo','コンゴ共和国','cg','cog','Congo');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('180','Congo, The Democratic Republic of the','コンゴ民主共和国','cd','cod','Congo-The-Democratic-Republic-of-the');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('184','Cook Islands','クック諸島','ck','cok','Cook-Islands');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('188','Costa Rica','コスタリカ共和国','cr','cri','Costa-Rica');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('384','Côte d\'Ivoire','コートジボワール共和国','ci','civ','Côte-d\'Ivoire');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('191','Croatia','クロアチア共和国','hr','hrv','Croatia');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('192','Cuba','キューバ共和国','cu','cub','Cuba');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('531','Curaçao','キュラソー','cw','cuw','Curaçao');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('196','Cyprus','キプロス共和国','cy','cyp','Cyprus');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('203','Czech Republic','チェコ共和国','cz','cze','Czech-Republic');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('208','Denmark','デンマーク王国','dk','dnk','Denmark');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('262','Djibouti','ジブチ共和国','dj','dji','Djibouti');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('212','Dominica','ドミニカ国','dm','dma','Dominica');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('214','Dominican Republic','ドミニカ共和国','do','dom','Dominican-Republic');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('218','Ecuador','エクアドル共和国','ec','ecu','Ecuador');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('818','Egypt','エジプト・アラブ共和国','eg','egy','Egypt');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('222','El Salvador','エルサルバドル共和国','sv','slv','El-Salvador');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('226','Equatorial Guinea','赤道ギニア共和国','gq','gnq','Equatorial-Guinea');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('232','Eritrea','エリトリア国','er','eri','Eritrea');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('233','Estonia','エストニア共和国','ee','est','Estonia');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('231','Ethiopia','エチオピア連邦民主共和国','et','eth','Ethiopia');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('238','Falkland Islands (Malvinas)','フォークランド(マルビナス)諸島','fk','flk','Falkland-Islands-(Malvinas)');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('234','Faroe Islands','フェロー諸島','fo','fro','Faroe-Islands');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('242','Fiji','フィジー諸島共和国','fj','fji','Fiji');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('246','Finland','フィンランド共和国','fi','fin','Finland');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('250','France','フランス共和国','fr','fra','France');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('254','French Guiana','フランス領ギアナ','gf','guf','French-Guiana');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('258','French Polynesia','フランス領ポリネシア','pf','pyf','French-Polynesia');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('260','French Southern Territories','フランス領極南諸島','tf','atf','French-Southern-Territories');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('266','Gabon','ガボン共和国','ga','gab','Gabon');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('270','Gambia','ガンビア共和国','gm','gmb','Gambia');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('268','Georgia','グルジア','ge','geo','Georgia');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('276','Germany','ドイツ連邦共和国','de','deu','Germany');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('288','Ghana','ガーナ共和国','gh','gha','Ghana');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('292','Gibraltar','ジブラルタル','gi','gib','Gibraltar');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('300','Greece','ギリシャ共和国','gr','grc','Greece');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('304','Greenland','グリーンランド','gl','grl','Greenland');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('308','Grenada','グレナダ','gd','grd','Grenada');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('312','Guadeloupe','グアドループ島','gp','glp','Guadeloupe');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('316','Guam','グアム','gu','gum','Guam');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('320','Guatemala','グアテマラ共和国','gt','gtm','Guatemala');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('831','Guernsey','ガーンジー島','gg','ggy','Guernsey');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('324','Guinea','ギニア共和国','gn','gin','Guinea');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('624','Guinea-Bissau','ギニアビサウ共和国','gw','gnb','Guinea-Bissau');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('328','Guyana','ガイアナ共和国','gy','guy','Guyana');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('332','Haiti','ハイチ共和国','ht','hti','Haiti');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('334','Heard Island and McDonald Islands','ハード島・マクドナルド諸島','hm','hmd','Heard-Island-and-McDonald-Islands');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('336','Holy See (Vatican City State)','バチカン市国','va','vat','Holy-See-(Vatican-City-State)');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('340','Honduras','ホンジュラス共和国','hn','hnd','Honduras');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('344','Hong Kong','ホンコン(香港)特別行政区','hk','hkg','Hong-Kong');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('348','Hungary','ハンガリー共和国','hu','hun','Hungary');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('352','Iceland','アイスランド共和国','is','isl','Iceland');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('356','India','インド','in','ind','India');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('360','Indonesia','インドネシア共和国','id','idn','Indonesia');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('364','Iran, Islamic Republic of','イラン・イスラム共和国','ir','irn','Iran-Islamic-Republic-of');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('368','Iraq','イラク共和国','iq','irq','Iraq');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('372','Ireland','アイルランド','ie','irl','Ireland');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('833','Isle of Man','マン島','im','imn','Isle-of-Man');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('376','Israel','イスラエル国','il','isr','Israel');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('380','Italy','イタリア共和国','it','ita','Italy');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('388','Jamaica','ジャマイカ','jm','jam','Jamaica');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('392','Japan','日本国','jp','jpn','Japan');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('832','Jersey','ジャージー島','je','jey','Jersey');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('400','Jordan','ヨルダン・ハシミテ王国','jo','jor','Jordan');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('398','Kazakhstan','カザフスタン共和国','kz','kaz','Kazakhstan');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('404','Kenya','ケニア共和国','ke','ken','Kenya');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('296','Kiribati','キリバス共和国','ki','kir','Kiribati');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('408','Korea, Democratic People\'s Republic of','北朝鮮＝朝鮮民主主義人民共和国','kp','prk','Korea-Democratic-People\'s-Republic-of');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('410','Korea, Republic of','大韓民国','kr','kor','Korea-Republic-of');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('414','Kuwait','クウェート国','kw','kwt','Kuwait');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('417','Kyrgyzstan','キルギス共和国','kg','kgz','Kyrgyzstan');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('418','Lao People\'s Democratic Republic','ラオス人民民主共和国','la','lao','Lao-People\'s-Democratic-Republic');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('428','Latvia','ラトビア共和国','lv','lva','Latvia');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('422','Lebanon','レバノン共和国','lb','lbn','Lebanon');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('426','Lesotho','レソト王国','ls','lso','Lesotho');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('430','Liberia','リベリア共和国','lr','lbr','Liberia');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('434','Libya','リビア','ly','lby','Libya');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('438','Liechtenstein','リヒテンシュタイン公国','li','lie','Liechtenstein');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('440','Lithuania','リトアニア共和国','lt','ltu','Lithuania');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('442','Luxembourg','ルクセンブルク大公国','lu','lux','Luxembourg');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('446','Macao','マカオ(澳門)特別行政区','mo','mac','Macao');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('807','Macedonia, the former Yugoslav Republic of','マケドニア旧ユーゴスラビア共和国','mk','mkd','Macedonia-the-former-Yugoslav-Republic-of');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('450','Madagascar','マダガスカル共和国','mg','mdg','Madagascar');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('454','Malawi','マラウイ共和国','mw','mwi','Malawi');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('458','Malaysia','マレーシア','my','mys','Malaysia');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('462','Maldives','モルディブ共和国','mv','mdv','Maldives');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('466','Mali','マリ共和国','ml','mli','Mali');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('470','Malta','マルタ共和国','mt','mlt','Malta');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('584','Marshall Islands','マーシャル諸島共和国','mh','mhl','Marshall-Islands');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('474','Martinique','マルチニーク島','mq','mtq','Martinique');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('478','Mauritania','モーリタニア・イスラム共和国','mr','mrt','Mauritania');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('480','Mauritius','モーリシャス共和国','mu','mus','Mauritius');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('175','Mayotte','マイヨット島','yt','myt','Mayotte');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('484','Mexico','メキシコ合衆国','mx','mex','Mexico');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('583','Micronesia, Federated States of','ミクロネシア連邦','fm','fsm','Micronesia-Federated-States-of');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('498','Moldova, Republic of','モルドバ共和国','md','mda','Moldova-Republic-of');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('492','Monaco','モナコ公国','mc','mco','Monaco');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('496','Mongolia','モンゴル国','mn','mng','Mongolia');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('499','Montenegro','モンテネグロ','me','mne','Montenegro');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('500','Montserrat','モントセラト','ms','msr','Montserrat');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('504','Morocco','モロッコ王国','ma','mar','Morocco');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('508','Mozambique','モザンビーク共和国','mz','moz','Mozambique');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('104','Myanmar','ミャンマー連邦','mm','mmr','Myanmar');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('516','Namibia','ナミビア共和国','na','nam','Namibia');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('520','Nauru','ナウル共和国','nr','nru','Nauru');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('524','Nepal','ネパール連邦民主共和国','np','npl','Nepal');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('528','Netherlands','オランダ王国','nl','nld','Netherlands');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('540','New Caledonia','ニューカレドニア','nc','ncl','New-Caledonia');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('554','New Zealand','ニュージーランド','nz','nzl','New-Zealand');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('558','Nicaragua','ニカラグア共和国','ni','nic','Nicaragua');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('562','Niger','ニジェール共和国','ne','ner','Niger');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('566','Nigeria','ナイジェリア連邦共和国','ng','nga','Nigeria');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('570','Niue','ニウエ','nu','niu','Niue');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('574','Norfolk Island','ノーフォーク島','nf','nfk','Norfolk-Island');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('580','Northern Mariana Islands','北マリアナ諸島','mp','mnp','Northern-Mariana-Islands');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('578','Norway','ノルウェー王国','no','nor','Norway');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('512','Oman','オマーン国','om','omn','Oman');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('586','Pakistan','パキスタン・イスラム共和国','pk','pak','Pakistan');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('585','Palau','パラオ共和国','pw','plw','Palau');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('275','Palestinian Territory, Occupied','西岸・ガザ(パレスチナ自治区)','ps','pse','Palestinian-Territory-Occupied');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('591','Panama','パナマ共和国','pa','pan','Panama');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('598','Papua New Guinea','パプアニューギニア独立国','pg','png','Papua-New-Guinea');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('600','Paraguay','パラグアイ共和国','py','pry','Paraguay');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('604','Peru','ペルー共和国','pe','per','Peru');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('608','Philippines','フィリピン共和国','ph','phl','Philippines');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('612','Pitcairn','ピトケアン諸島','pn','pcn','Pitcairn');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('616','Poland','ポーランド共和国','pl','pol','Poland');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('620','Portugal','ポルトガル共和国','pt','prt','Portugal');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('630','Puerto Rico','プエルトリコ','pr','pri','Puerto-Rico');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('634','Qatar','カタール国','qa','qat','Qatar');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('638','Réunion','レユニオン','re','reu','Réunion');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('642','Romania','ルーマニア','ro','rou','Romania');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('643','Russian Federation','ロシア連邦','ru','rus','Russian-Federation');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('646','Rwanda','ルワンダ共和国','rw','rwa','Rwanda');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('652','Saint Barthélemy','サンバルテルミー','bl','blm','Saint-Barthélemy');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('654','Saint Helena, Ascension and Tristan da Cunha','セントヘレナ・アセンション・トリスタンダクーニャ','sh','shn','Saint-Helena-Ascension-and-Tristan-da-Cunha');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('659','Saint Kitts and Nevis','セントキッツ・ネービス','kn','kna','Saint-Kitts-and-Nevis');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('662','Saint Lucia','セントルシア','lc','lca','Saint-Lucia');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('663','Saint Martin (French part)','サンマルタン','mf','maf','Saint-Martin-(French-part)');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('666','Saint Pierre and Miquelon','サンピエール島・ミクロン島','pm','spm','Saint-Pierre-and-Miquelon');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('670','Saint Vincent and the Grenadines','セントビンセント・グレナディーン諸島','vc','vct','Saint-Vincent-and-the-Grenadines');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('882','Samoa','サモア独立国','ws','wsm','Samoa');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('674','San Marino','サンマリノ共和国','sm','smr','San-Marino');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('678','Sao Tome and Principe','サントメ・プリンシペ民主共和国','st','stp','Sao-Tome-and-Principe');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('682','Saudi Arabia','サウジアラビア王国','sa','sau','Saudi-Arabia');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('686','Senegal','セネガル共和国','sn','sen','Senegal');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('688','Serbia','セルビア共和国','rs','srb','Serbia');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('690','Seychelles','セーシェル共和国','sc','syc','Seychelles');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('694','Sierra Leone','シエラレオネ共和国','sl','sle','Sierra-Leone');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('702','Singapore','シンガポール共和国','sg','sgp','Singapore');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('534','Sint Maarten (Dutch part)','シント・マールテン(オランダ領)','sx','sxm','Sint-Maarten-(Dutch-part)');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('703','Slovakia','スロバキア共和国','sk','svk','Slovakia');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('705','Slovenia','スロベニア共和国','si','svn','Slovenia');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('90','Solomon Islands','ソロモン諸島','sb','slb','Solomon-Islands');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('706','Somalia','ソマリア民主共和国','so','som','Somalia');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('710','South Africa','南アフリカ共和国','za','zaf','South-Africa');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('239','South Georgia and the South Sandwich Islands','南ジョージア島・南サンドイッチ諸島','gs','sgs','South-Georgia-and-the-South-Sandwich-Islands');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('728','South Sudan','南スーダン','ss','ssd','South-Sudan');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('724','Spain','スペイン','es','esp','Spain');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('144','Sri Lanka','スリランカ民主社会主義共和国','lk','lka','Sri-Lanka');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('736','Sudan','スーダン共和国','sd','sdn','Sudan');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('740','Suriname','スリナム共和国','sr','sur','Suriname');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('744','Svalbard and Jan Mayen','スバールバル諸島・ヤンマイエン島','sj','sjm','Svalbard-and-Jan-Mayen');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('748','Swaziland','スワジランド王国','sz','swz','Swaziland');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('752','Sweden','スウェーデン王国','se','swe','Sweden');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('756','Switzerland','スイス連邦','ch','che','Switzerland');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('760','Syrian Arab Republic','シリア・アラブ共和国','sy','syr','Syrian-Arab-Republic');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('158','Taiwan, Province of China','台湾','tw','twn','Taiwan-Province-of-China');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('762','Tajikistan','タジキスタン共和国','tj','tjk','Tajikistan');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('834','Tanzania, United Republic of','タンザニア連合共和国','tz','tza','Tanzania-United-Republic-of');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('764','Thailand','タイ王国','th','tha','Thailand');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('626','Timor-Leste','東ティモール民主共和国','tl','tls','Timor-Leste');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('768','Togo','トーゴ共和国','tg','tgo','Togo');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('772','Tokelau','トケラウ諸島','tk','tkl','Tokelau');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('776','Tonga','トンガ王国','to','ton','Tonga');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('780','Trinidad and Tobago','トリニダード・トバゴ共和国','tt','tto','Trinidad-and-Tobago');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('788','Tunisia','チュニジア共和国','tn','tun','Tunisia');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('792','Turkey','トルコ共和国','tr','tur','Turkey');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('795','Turkmenistan','トルクメニスタン','tm','tkm','Turkmenistan');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('796','Turks and Caicos Islands','タークス・カイコス諸島','tc','tca','Turks-and-Caicos-Islands');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('798','Tuvalu','ツバル','tv','tuv','Tuvalu');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('800','Uganda','ウガンダ共和国','ug','uga','Uganda');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('804','Ukraine','ウクライナ','ua','ukr','Ukraine');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('784','United Arab Emirates','アラブ首長国連邦','ae','are','United-Arab-Emirates');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('826','United Kingdom','グレートブリテン・北アイルランド連合王国(英国)','gb','gbr','United-Kingdom');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('840','United States','アメリカ合衆国','us','usa','United-States');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('581','United States Minor Outlying Islands','米領小離島','um','umi','United-States-Minor-Outlying-Islands');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('858','Uruguay','ウルグアイ東方共和国','uy','ury','Uruguay');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('860','Uzbekistan','ウズベキスタン共和国','uz','uzb','Uzbekistan');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('548','Vanuatu','バヌアツ共和国','vu','vut','Vanuatu');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('862','Venezuela, Bolivarian Republic of','ベネズエラ・ボリバル共和国','ve','ven','Venezuela-Bolivarian-Republic-of');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('704','Viet Nam','ベトナム社会主義共和国','vn','vnm','Viet-Nam');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('92','Virgin Islands, British','英領バージン諸島','vg','vgb','Virgin-Islands-British');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('850','Virgin Islands, U.S.','米領バージン諸島','vi','vir','Virgin-Islands-U.S.');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('876','Wallis and Futuna','ワリス・フテュナ諸島','wf','wlf','Wallis-and-Futuna');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('732','Western Sahara','西サハラ','eh','esh','Western-Sahara');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('887','Yemen','イエメン共和国','ye','yem','Yemen');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('894','Zambia','ザンビア共和国','zm','zmb','Zambia');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('716','Zimbabwe','ジンバブエ共和国','zw','zwe','Zimbabwe');
INSERT INTO m_country (id,name_en,name_ja,iso_2,iso_3,icon_base) values ('1000','Former HRE','旧東フランク王国','d1','d11','');
